### ISSUE TITLE
解决使用 Win10 共享移动热点无法连接互联网的问题

### ISSUE THREAD

**Issue by Ruikuan** [Ruikuan/blog#51]
Windows 10 自带了个移动热点功能，通常来说，直接点一下，它就创建一个移动热点，给手机或者其他电脑用 wifi 连接过去，共享网络。

不过今天我试用一下，发现手机虽然能连上了 wifi，但却显示无法连接到互联网，分配到的 ip 为 192.168.170.*（？）。

电脑是新重装不到两天，系统应该暂时不会出什么问题。看来是配置的问题了。尝试打开`以太网`连接（笔记本上的有线网卡）的属性，查看了共享 Tab，共享状态没有选中。选中它，然后共享给虚拟出来的那个热点连接。无效，症状还是一样。

想了下，机器跑了 Hyper-V，而 Hyper-V 使用`以太网`创建了个虚拟交换机，在控制面板里面显示目前连接的网络连接是`vEthernet (Intel 82579LM Gigabit Switch)`的网口，其中`Intel 82579LM Gigabit *` 是我的有线网卡的型号。于是查看`vEthernet (Intel 82579LM Gigabit Switch)`连接的属性，看共享 Tab，没有共享。将它共享给热点连接，这下手机能连上外网了，问题解决。而且 Hyper-V 虚拟机的网络也没有受到影响。

**Comment by brucmao** [comment]
感谢博主，我将Hyper-V的虚拟网卡共享给移动热点就可以使用手机热点了。我还搜到一篇博客可以新建一个NAT 实例，有空尝试下
https://kenvix.com/post/setup-nat-on-windows/

**Comment by LetMeFly666** [comment]
@brucmao @Ruikuan 👍

**Comment by brucmao** [comment]
@LetMeFly666 好巧，你也在看这个问题

**Comment by LetMeFly666** [comment]
@brucmao 哈哈是的呢，向你学习

**Comment by cckk4467** [comment]
谢谢博主，原来是要给Hyper-V的虚拟交换机设置共享，问题就解决了。就是不知道什么原理

**Comment by SurfenV** [comment]
感谢，困扰我好久的问题，终于解决了！
